// Generated by `mise run codegen` — do not edit.
// Source: codegen/Sources/CrispChatBoxFFI/CrispClient.swift
// swiftformat:options --func-attributes same-line

import CrispDomain
import CrispUtils
import Foundation

package struct CrispClient {
  @MainActor package func injectMessage(_ message: Message) async throws {
    let caller = JSCaller(
      funcName: "\(Self._jsClassName).injectMessage",
      evaluator: self.evaluator,
    )
    return try await caller(jsEncode(message))
  }

  @MainActor package func focusOnForeground() async throws {
    let caller = JSCaller(
      funcName: "\(Self._jsClassName).focusOnForeground",
      evaluator: self.evaluator,
    )
    return try await caller()
  }

  @MainActor package func registerNotification(deviceToken: String) async throws {
    let caller = JSCaller(
      funcName: "\(Self._jsClassName).registerNotification",
      evaluator: self.evaluator,
    )
    return try await caller(jsEncode(deviceToken))
  }

  @MainActor package func unregisterNotification(deviceToken: String) async throws {
    let caller = JSCaller(
      funcName: "\(Self._jsClassName).unregisterNotification",
      evaluator: self.evaluator,
    )
    return try await caller(jsEncode(deviceToken))
  }

  @MainActor package func connectSocket() async throws {
    let caller = JSCaller(
      funcName: "\(Self._jsClassName).connectSocket",
      evaluator: self.evaluator,
    )
    return try await caller()
  }

  @MainActor package func disconnectSocket() async throws {
    let caller = JSCaller(
      funcName: "\(Self._jsClassName).disconnectSocket",
      evaluator: self.evaluator,
    )
    return try await caller()
  }

  @MainActor package func helpdeskArticleOpen(
    locale: LanguageCode,
    slug: String,
    title: String?,
    category: String?,
  ) async throws {
    let caller = JSCaller(
      funcName: "\(Self._jsClassName).helpdeskArticleOpen",
      evaluator: self.evaluator,
    )
    return try await caller(jsEncode(locale), jsEncode(slug), jsEncode(title), jsEncode(category))
  }

  @MainActor package func helpdeskSearch() async throws {
    let caller = JSCaller(
      funcName: "\(Self._jsClassName).helpdeskSearch",
      evaluator: self.evaluator,
    )
    return try await caller()
  }

  @MainActor package func chatShow() async throws {
    let caller = JSCaller(
      funcName: "\(Self._jsClassName).chatShow",
      evaluator: self.evaluator,
    )
    return try await caller()
  }

  @MainActor package func botScenarioRun(id: BotScenarioId) async throws {
    let caller = JSCaller(
      funcName: "\(Self._jsClassName).botScenarioRun",
      evaluator: self.evaluator,
    )
    return try await caller(jsEncode(id))
  }

  @MainActor package func getSessionIdentifier() async throws -> SessionId {
    let caller = JSCaller(
      funcName: "\(Self._jsClassName).getSessionIdentifier",
      evaluator: self.evaluator,
    )
    return try await caller()
  }

  @MainActor package func isSessionOngoing() async throws -> Bool {
    let caller = JSCaller(
      funcName: "\(Self._jsClassName).isSessionOngoing",
      evaluator: self.evaluator,
    )
    return try await caller()
  }

  @MainActor package func messageShow(
    type: ConversationMessageType,
    content: ConversationMessageContent,
    fingerprint: MessageFingerprint?,
    prepend: Bool?,
  ) async throws {
    let caller = JSCaller(
      funcName: "\(Self._jsClassName).messageShow",
      evaluator: self.evaluator,
    )
    return try await caller(
      jsEncode(type),
      jsEncode(content),
      jsEncode(fingerprint),
      jsEncode(prepend),
    )
  }

  @MainActor package func getMessages() async throws -> [LocalMessage] {
    let caller = JSCaller(
      funcName: "\(Self._jsClassName).getMessages",
      evaluator: self.evaluator,
    )
    return try await caller()
  }

  @MainActor package func setSessionData(_ data: [Tuple]) async throws {
    let caller = JSCaller(
      funcName: "\(Self._jsClassName).setSessionData",
      evaluator: self.evaluator,
    )
    return try await caller(jsEncode(data))
  }

  @MainActor package func getSessionData(key: String?) async throws -> JSONValue {
    let caller = JSCaller(
      funcName: "\(Self._jsClassName).getSessionData",
      evaluator: self.evaluator,
    )
    return try await caller(jsEncode(key))
  }

  @MainActor package func setSessionSegments(_ segments: [String], overwrite: Bool?) async throws {
    let caller = JSCaller(
      funcName: "\(Self._jsClassName).setSessionSegments",
      evaluator: self.evaluator,
    )
    return try await caller(jsEncode(segments), jsEncode(overwrite))
  }

  @MainActor package func setSessionEvent(
    name: String,
    data: [String: AnyEncodable]?,
    color: SessionEvent.Color?,
  ) async throws {
    let caller = JSCaller(
      funcName: "\(Self._jsClassName).setSessionEvent",
      evaluator: self.evaluator,
    )
    return try await caller(jsEncode(name), jsEncode(data), jsEncode(color))
  }

  @MainActor package func setUserEmail(_ email: String?, signature: String?) async throws {
    let caller = JSCaller(
      funcName: "\(Self._jsClassName).setUserEmail",
      evaluator: self.evaluator,
    )
    return try await caller(jsEncode(email), jsEncode(signature))
  }

  @MainActor package func getUserEmail() async throws -> String? {
    let caller = JSCaller(
      funcName: "\(Self._jsClassName).getUserEmail",
      evaluator: self.evaluator,
    )
    return try await caller()
  }

  @MainActor package func setUserPhone(_ phone: String?) async throws {
    let caller = JSCaller(
      funcName: "\(Self._jsClassName).setUserPhone",
      evaluator: self.evaluator,
    )
    return try await caller(jsEncode(phone))
  }

  @MainActor package func getUserPhone() async throws -> String? {
    let caller = JSCaller(
      funcName: "\(Self._jsClassName).getUserPhone",
      evaluator: self.evaluator,
    )
    return try await caller()
  }

  @MainActor package func setUserNickname(_ nickname: String?) async throws {
    let caller = JSCaller(
      funcName: "\(Self._jsClassName).setUserNickname",
      evaluator: self.evaluator,
    )
    return try await caller(jsEncode(nickname))
  }

  @MainActor package func getUserNickname() async throws -> String? {
    let caller = JSCaller(
      funcName: "\(Self._jsClassName).getUserNickname",
      evaluator: self.evaluator,
    )
    return try await caller()
  }

  @MainActor package func setUserAvatar(_ url: URL?) async throws {
    let caller = JSCaller(
      funcName: "\(Self._jsClassName).setUserAvatar",
      evaluator: self.evaluator,
    )
    return try await caller(jsEncode(url))
  }

  @MainActor package func getUserAvatar() async throws -> URL? {
    let caller = JSCaller(
      funcName: "\(Self._jsClassName).getUserAvatar",
      evaluator: self.evaluator,
    )
    return try await caller()
  }

  @MainActor package func setUserCompany(name: String, company: Company?) async throws {
    let caller = JSCaller(
      funcName: "\(Self._jsClassName).setUserCompany",
      evaluator: self.evaluator,
    )
    return try await caller(jsEncode(name), jsEncode(company))
  }

  @MainActor package func getUserCompany() async throws -> Company? {
    let caller = JSCaller(
      funcName: "\(Self._jsClassName).getUserCompany",
      evaluator: self.evaluator,
    )
    return try await caller()
  }

  @MainActor package func reset() async throws {
    let caller = JSCaller(
      funcName: "\(Self._jsClassName).reset",
      evaluator: self.evaluator,
    )
    return try await caller()
  }

  @MainActor package func onInterfaceLifecycle(
    _ handler: @MainActor @escaping (InterfaceLifecycleEvent) -> Void,
  ) {
    self.events.register("onInterfaceLifecycle", JSEventHandler(handler))
  }

  @MainActor
  package func onInterfaceAction(_ handler: @MainActor @escaping (InterfaceActionEvent) -> Void) {
    self.events.register("onInterfaceAction", JSEventHandler(handler))
  }

  @MainActor package func onMessageSent(_ handler: @MainActor @escaping (Message) -> Void) {
    self.events.register("onMessageSent", JSEventHandler(handler))
  }

  @MainActor package func onMessageReceived(_ handler: @MainActor @escaping (Message) -> Void) {
    self.events.register("onMessageReceived", JSEventHandler(handler))
  }

  private let evaluator: JSEvaluator

  let events: JSEventBus

  static let _jsClassName: String = "CrispClient"

  @MainActor package init(evaluator: @escaping JSEvaluator, events: JSEventBus) {
    self.evaluator = evaluator
    self.events = events
  }

  @MainActor package func onEventError(
    _ handler: @MainActor @escaping (String, JSEventError) -> Void,
  ) {
    self.events.onError(handler)
  }

  nonisolated static let generatedJS: String = #"""
  import {
    botScenarioRun,
    chatShow,
    connectSocket,
    disconnectSocket,
    focusOnForeground,
    getMessages,
    getSessionData,
    getSessionIdentifier,
    getUserAvatar,
    getUserCompany,
    getUserEmail,
    getUserNickname,
    getUserPhone,
    helpdeskArticleOpen,
    helpdeskSearch,
    injectMessage,
    isSessionOngoing,
    messageShow,
    on,
    onInterfaceAction,
    onInterfaceLifecycle,
    registerNotification,
    reset,
    setSessionData,
    setSessionEvent,
    setSessionSegments,
    setUserAvatar,
    setUserCompany,
    setUserEmail,
    setUserNickname,
    setUserPhone,
    unregisterNotification,
  } from './crisp-client.js'

  window.CrispClient = {
    botScenarioRun,
    chatShow,
    connectSocket,
    disconnectSocket,
    focusOnForeground,
    getMessages,
    getSessionData,
    getSessionIdentifier,
    getUserAvatar,
    getUserCompany,
    getUserEmail,
    getUserNickname,
    getUserPhone,
    helpdeskArticleOpen,
    helpdeskSearch,
    injectMessage: globalThis.injectMessageEnvelope,
    isSessionOngoing,
    messageShow,
    registerNotification,
    reset,
    setSessionData,
    setSessionEvent,
    setSessionSegments,
    setUserAvatar,
    setUserCompany,
    setUserEmail,
    setUserNickname,
    setUserPhone,
    unregisterNotification,
  }

  onInterfaceAction((payload) => sendEvent('onInterfaceAction', payload))
  onInterfaceLifecycle((payload) => sendEvent('onInterfaceLifecycle', payload))
  on("message:received", (payload) => sendEvent("onMessageReceived", payload))
  on("message:sent", (payload) => sendEvent("onMessageSent", payload))
  """#
}

package extension CrispClient {
  struct InterfaceLifecycleEvent: Decodable {
    package enum State: String, Decodable {
      case mounted
      case ready
      case unmounted
      case error
    }

    package struct Data: Decodable {
      package let origin: String?
    }

    package let state: State
    package let data: Data?
  }

  struct InterfaceActionEvent: Decodable {
    package enum Action: String, Decodable {
      case close
      case upload
      case speech
      case select
      case download
    }

    package struct Data: Decodable {
      package enum State: String, Decodable {
        case record
        case cancel
        case send
      }

      package enum Object: String, Decodable {
        case message
      }

      package struct File: Decodable {
        package let type: String
        package let url: URL
        package let name: String
      }

      package struct Pointer: Decodable {
        package let x: Double
        package let y: Double
      }

      package let origin: String?
      package let state: State?
      package let object: Object?
      package let target: LocalMessage?
      package let file: File?
      package let pointer: Pointer?
    }

    package let action: Action
    package let data: Data?
  }
}

/// Extension to communicate with hand-written JS code
@MainActor package extension CrispClient {
  /// Emitted when the user taps a button on a `picker` message that was injected
  /// from native via `CrispEx.injectMessage(...)`. The IndexHTML installer
  /// attaches a per-choice `handler` callback that posts this event back.
  struct PickerClickEvent: Decodable {
    package let fingerprint: MessageFingerprint
    package let pickerId: PickerId
    package let choiceValue: String

    private enum CodingKeys: String, CodingKey {
      case fingerprint
      case pickerId = "picker_id"
      case choiceValue = "choice_value"
    }
  }

  /// Forwarded from the JS `LogSink` callback installed by `connectLogger`.
  /// Mirrors the `(level, ns, value)` triplet emitted from `LoggerHelper`.
  struct LogEvent: Decodable {
    package enum Level: String, Decodable {
      case error, warn, info, log, debug
      case unknown

      package init(from decoder: any Decoder) throws {
        let container = try decoder.singleValueContainer()
        let raw = try container.decode(String.self)
        self = Self(rawValue: raw) ?? .unknown
      }
    }

    package let level: Level
    package let ns: String
    package let value: String
  }

  /// Emitted when the IndexHTML script encounters an uncaught error or an
  /// unhandled promise rejection. Covers module-load failures (e.g. a
  /// non-existent import) that would otherwise surface only as a DOM-ready
  /// timeout ~10 seconds later.
  struct ScriptErrorEvent: Equatable, Decodable {
    package enum Source: String, Equatable, Decodable {
      case error
      case unhandledRejection = "unhandledrejection"
    }

    package let source: Source
    package let message: String
    package let filename: String?
    package let line: Int?
    package let col: Int?
    package let stack: String?
  }

  func onPickerClick(_ handler: @MainActor @escaping (PickerClickEvent) -> Void) {
    self.events.register("onPickerClick", .init(handler))
  }

  func onLog(_ handler: @MainActor @escaping (LogEvent) -> Void) {
    self.events.register("onLog", .init(handler))
  }

  func onScriptError(_ handler: @MainActor @escaping (ScriptErrorEvent) -> Void) {
    self.events.register("onScriptError", .init(handler))
  }
}
