min_version = "2025.9.23"

[env]
CRISP_CLIENT_NPM_PACKAGE = "@crisp/crisp-client"
CRISP_CLIENT_OP_ITEM = "Crisp SDK npm Pull Token"
CRISP_SDK_REPO = "crisp-im/crisp-sdk-ios"
SIGNING_IDENTITY = "Apple Distribution: Crisp IM SARL (26V2WGBKY3)"

CRISP_CLIENT_XCFRAMEWORK_DIR = "{{env.PWD}}/Sources/CrispClient/CrispClient.xcframework"
BUILD_DIR = "{{env.PWD}}/.build"

[tools]
swiftformat = "0.61.1"
swiftgen = "6.6.3"
swiftlint = "0.63.2"
xcbeautify = "3.2.1"
jq = "1.8.1"
node = "24.1.0"
ruby = "3.3"
cocoapods = "1.16.2"
"spm:appdecostudio/SwiftPolyglot" = "v2.0.2"

[tasks.format]
description = "Run swiftformat"
alias = "f"
run = ["swiftformat ."]

[tasks.lint]
description = "Run swiftlint"
alias = "l"
run = ["swiftlint lint --quiet"]

[tasks.codegen]
description = "Expand Swift Macros used for CrispClient"
run = ["swift run --package-path codegen MacroExpander"]
depends_post = ["format"]

[tasks.validate-translations]
description = "Verify that all translations are present"
run = ["swiftpolyglot --error-on-missing"]
