import Foundation
import SwiftParser
import SwiftSyntax
import SwiftSyntaxMacroExpansion
import SwiftSyntaxMacros

// Expands the macro-annotated sources under codegen/Sources/** and writes
// plain Swift to the mirrored path under Sources/**. The root package vends
// the generated output and has no swift-syntax dependency.
//
// A file is processed only if it actually uses one of our macro attributes
// (@JSClass / @JSMethod / @JSEvent / @CrispActionEvent). That keeps the
// expander from touching macro declarations, plugin scaffolding, or files
// reached via symlinks (e.g. JSInfra/, Types/).

let macros: [String: Macro.Type] = [
  "JSClass": JSClassMacro.self,
  "JSMethod": JSMethodMacro.self,
  "JSEvent": JSEventMacro.self,
  "CrispActionEvent": CrispActionEventMacro.self,
]

struct CodegenError: Error, CustomStringConvertible {
  let description: String
}

final class MacroAttributeFinder: SyntaxVisitor {
  let macroNames: Set<String>
  var found = false

  init(_ names: Set<String>) {
    self.macroNames = names
    super.init(viewMode: .sourceAccurate)
  }

  override func visit(_ node: AttributeSyntax) -> SyntaxVisitorContinueKind {
    if let id = node.attributeName.as(IdentifierTypeSyntax.self),
       self.macroNames.contains(id.name.text)
    {
      self.found = true
      return .skipChildren
    }
    return .visitChildren
  }
}

func usesMacros(_ source: SourceFileSyntax) -> Bool {
  let finder = MacroAttributeFinder(Set(macros.keys))
  finder.walk(source)
  return finder.found
}

func run() throws {
  let fm = FileManager.default
  let repoRoot = URL(
    fileURLWithPath: CommandLine.arguments.count > 1
      ? CommandLine.arguments[1]
      : fm.currentDirectoryPath,
  )
  let inputRoot = repoRoot.appendingPathComponent("codegen/Sources").standardizedFileURL
  let outputRoot = repoRoot.appendingPathComponent("Sources").standardizedFileURL

  guard fm.fileExists(atPath: inputRoot.path) else {
    throw CodegenError(description: "no codegen/Sources directory at \(inputRoot.path)")
  }
  guard let walker = fm.enumerator(at: inputRoot, includingPropertiesForKeys: nil) else {
    throw CodegenError(description: "could not enumerate \(inputRoot.path)")
  }

  for case let fileURL as URL in walker
    where fileURL.pathExtension == "swift"
  {
    let source = try String(contentsOf: fileURL, encoding: .utf8)
    let sourceFile = Parser.parse(source: source)

    guard usesMacros(sourceFile) else {
      continue
    }

    let relPath = fileURL.standardizedFileURL.path
      .replacingOccurrences(of: inputRoot.path + "/", with: "")
    let outURL = outputRoot.appendingPathComponent(relPath)
    let moduleName = relPath.split(separator: "/").first.map(String.init) ?? "Generated"

    let context = BasicMacroExpansionContext(
      sourceFiles: [
        sourceFile: .init(moduleName: moduleName, fullFilePath: fileURL.path),
      ],
    )
    let expanded = sourceFile.expand(
      macros: macros,
      contextGenerator: { syntax in
        BasicMacroExpansionContext(
          sharingWith: context,
          lexicalContext: syntax.allMacroLexicalContexts(),
        )
      },
      indentationWidth: .spaces(2),
    ).description

    try fm.createDirectory(
      at: outURL.deletingLastPathComponent(),
      withIntermediateDirectories: true,
    )
    try expanded.write(to: outURL, atomically: true, encoding: .utf8)

    let formatted = try String(contentsOf: outURL, encoding: .utf8)
    let banner = """
    // Generated by `mise run codegen` — do not edit.
    // Source: codegen/Sources/\(relPath)
    // swiftformat:options --func-attributes same-line


    """

    try (banner + formatted).write(to: outURL, atomically: true, encoding: .utf8)
  }
}

try run()
